allStims = [
  {noun: "pencil", adjective: "long", fileinit: "pencilLong", range:[[1,4], [3,4]]},
  {noun: "pencil", adjective: "short", fileinit: "pencilLong", range:[[9,6], [9,8]]},
  {noun: "glass", adjective: "tall", fileinit: "glassTall", range:[[1,4], [3,4]]},
  {noun: "glass", adjective: "short", fileinit: "glassTall", range:[[9,6], [9,8]]},
  {noun: "strawberry", adjective: "big", fileinit: "strawberryBig", range:[[1,4], [3,4]]},
  {noun: "strawberry", adjective: "small", fileinit: "strawberryBig", range:[[9,6], [9,8]]},
  {noun: "cat", adjective: "fat", fileinit: "catFat", range:[[1,4], [3,4]]},
  {noun: "cat", adjective: "thin", fileinit: "catFat", range:[[9,6], [9,8]]},
  {noun: "book", adjective: "thick", fileinit: "bookThick", range:[[1,4], [3,4]]},
  {noun: "book", adjective: "thin", fileinit: "bookThick", range:[[9,6], [9,8]]},
  {noun: "ladder", adjective: "wide", fileinit: "ladderWide", range:[[1,4], [3,4]]},
  {noun: "ladder", adjective: "narrow", fileinit: "ladderWide", range:[[9,6], [9,8]]},
  {noun: "bowl", adjective: "deep", fileinit: "bowlDeep", range:[[1,4], [3,4]]},
  {noun: "bowl", adjective: "shallow", fileinit: "bowlDeep", range:[[9,6], [9,8]]},
  {noun: "cloud", adjective: "high", fileinit: "cloudHigh", range:[[1,4], [3,4]]},
  {noun: "cloud", adjective: "low", fileinit: "cloudHigh", range:[[9,6], [9,8]]},
  {noun: "rectangle", adjective: "dark", fileinit: "rectangleDark", range:[[1,4], [3,4]]},
  {noun: "rectangle", adjective: "light", fileinit: "rectangleDark", range:[[9,6], [9,8]]},
  {noun: "banana", adjective: "ripe", fileinit: "bananaRipe", range:[[1,4], [3,4]]},
  {noun: "banana", adjective: "raw", fileinit: "bananaRipe", range:[[9,6], [9,8]]},
  {noun: "glass", adjective: "full", fileinit: "glassFull", range:[[2,5], [4,5]]},
  {noun: "glass", adjective: "empty", fileinit: "glassFull", range:[[5,2], [3,2]]},
  {noun: "gate", adjective: "open", fileinit: "gateOpen", range:[[2,5], [4,5]]},
  {noun: "gate", adjective: "closed", fileinit: "gateOpen", range:[[6,3], [4,3]]},
  {noun: "glass", adjective: "transparent", fileinit: "glassTransparent", range:[[2,5], [4,5]]},
  {noun: "glass", adjective: "opaque", fileinit: "glassTransparent", range:[[6,3], [4,3]]},
  {noun: "straw", adjective: "straight", fileinit: "strawStraight", range:[[5,8], [7,8]]},
  {noun: "straw", adjective: "bent", fileinit: "strawStraight", range:[[8,5], [8,7]]},
  {noun: "cookie", adjective: "round", fileinit: "cookieRound", range:[[6,7], [4,7]]},
  {noun: "plate", adjective: "clean", fileinit: "plateClean", range:[[5,8], [7,8]]},
  {noun: "plate", adjective: "dirty", fileinit: "plateClean", range:[[8,5], [6,5]]},
  {noun: "toast", adjective: "burnt", fileinit: "toastBurnt", range:[[5,6], [3,6]]},
  {noun: "paper", adjective: "torn", fileinit: "paperTorn", range:[[2,3], [2,4]]},
  {noun: "sky", adjective: "cloudy", fileinit: "skyCloudy", range:[[3,4], [2,4]]},
];

allStims = _.shuffle(allStims);
