allStims = [
  {noun: "pencil", adjective: "long", fileinit: "pencilLong", range:[1,4,6,9]},
  {noun: "pencil", adjective: "short", fileinit: "pencilLong", range:[1,4,6,9]},
  {noun: "glass", adjective: "tall", fileinit: "glassTall", range:[1,4,6,9]},
  {noun: "glass", adjective: "short", fileinit: "glassTall", range:[1,4,6,9]},
  {noun: "strawberry", adjective: "big", fileinit: "strawberryBig", range:[1,4,6,9]},
  {noun: "strawberry", adjective: "small", fileinit: "strawberryBig", range:[1,4,6,9]},
  {noun: "cat", adjective: "fat", fileinit: "catFat", range:[1,4,6,9]},
  {noun: "cat", adjective: "thin", fileinit: "catFat", range:[1,4,6,9]},
  {noun: "book", adjective: "thick", fileinit: "bookThick", range:[1,4,6,9]},
  {noun: "book", adjective: "thin", fileinit: "bookThick", range:[1,4,6,9]},
  {noun: "ladder", adjective: "wide", fileinit: "ladderWide", range:[1,4,6,9]},
  {noun: "ladder", adjective: "narrow", fileinit: "ladderWide", range:[1,4,6,9]},
  {noun: "bowl", adjective: "deep", fileinit: "bowlDeep", range:[1,4,6,9]},
  {noun: "bowl", adjective: "shallow", fileinit: "bowlDeep", range:[1,4,6,9]},
  {noun: "cloud", adjective: "high", fileinit: "cloudHigh", range:[1,4,6,9]},
  {noun: "cloud", adjective: "low", fileinit: "cloudHigh", range:[1,4,6,9]},
  {noun: "rectangle", adjective: "dark", fileinit: "rectangleDark", range:[4,6,8,9]},
  {noun: "rectangle", adjective: "light", fileinit: "rectangleDark", range:[1,2,4,6]},
  {noun: "banana", adjective: "ripe", fileinit: "bananaRipe", range:[4,6,8,9]},
  {noun: "banana", adjective: "raw", fileinit: "bananaRipe", range:[1,2,4,6]},
  {noun: "glass", adjective: "full", fileinit: "glassFull", range:[4,6,8,9]},
  {noun: "glass", adjective: "empty", fileinit: "glassFull", range:[1,2,4,6]},
  {noun: "glass", adjective: "transparent", fileinit: "glassTransparent", range:[1,4,6,9]},
  {noun: "glass", adjective: "opaque", fileinit: "glassTransparent", range:[1,4,6,9]},
  {noun: "gate", adjective: "open", fileinit: "gateOpen", range:[2,4,6,9]},
  {noun: "gate", adjective: "closed", fileinit: "gateOpen", range:[1,2,3,4]},
  {noun: "straw", adjective: "straight", fileinit: "strawStraight", range:[6,7,8,9]},
  {noun: "straw", adjective: "bent", fileinit: "strawStraight", range:[6,7,8,9]},
  {noun: "cookie", adjective: "round", fileinit: "cookieRound", range:[2,4,6,8]},
  {noun: "plate", adjective: "clean", fileinit: "plateClean", range:[6,7,8,9]},
  {noun: "plate", adjective: "dirty", fileinit: "plateClean", range:[6,7,8,9]},
  {noun: "toast", adjective: "burnt", fileinit: "toastBurnt", range:[2,4,6,8]},
  {noun: "paper", adjective: "torn", fileinit: "paperTorn", range:[1,2,3,4]},
  {noun: "sky", adjective: "cloudy", fileinit: "skyCloudy", range:[1,2,4,6]},
];

allStims = _.shuffle(allStims);
