allStims = [
  {noun: "pencil", adjective: "long", fileinit: "pencilLong", range:[[1,4], [3,4]], comp: "longer"},
  {noun: "pencil", adjective: "short", fileinit: "pencilLong", range:[[9,6], [7,6]], comp: "shorter"},
  {noun: "glass", adjective: "tall", fileinit: "glassTall", range:[[1,4], [3,4]], comp: "taller"},
  {noun: "glass", adjective: "short", fileinit: "glassTall", range:[[9,6], [7,6]], comp: "shorter"},
  {noun: "strawberry", adjective: "big", fileinit: "strawberryBig", range:[[1,4], [3,4]], comp: "bigger"},
  {noun: "strawberry", adjective: "small", fileinit: "strawberryBig", range:[[9,6], [7,6]], comp: "smaller"},
  {noun: "cat", adjective: "fat", fileinit: "catFat", range:[[1,4], [3,4]], comp: "fatter"},
  {noun: "cat", adjective: "thin", fileinit: "catFat", range:[[9,6], [7,6]], comp: "thinner"},
  {noun: "book", adjective: "thick", fileinit: "bookThick", range:[[1,4], [3,4]], comp: "thicker"},
  {noun: "book", adjective: "thin", fileinit: "bookThick", range:[[9,6], [7,6]], comp: "thinner"},
  {noun: "ladder", adjective: "wide", fileinit: "ladderWide", range:[[1,4], [3,4]], comp: "wider"},
  {noun: "ladder", adjective: "narrow", fileinit: "ladderWide", range:[[9,6], [7,6]], comp: "narrower"},
  {noun: "bowl", adjective: "deep", fileinit: "bowlDeep", range:[[1,4], [3,4]], comp: "deeper"},
  {noun: "bowl", adjective: "shallow", fileinit: "bowlDeep", range:[[9,6], [7,6]], comp: "shallower"},
  {noun: "cloud", adjective: "high", fileinit: "cloudHigh", range:[[1,4], [3,4]], comp: "higher"},
  {noun: "cloud", adjective: "low", fileinit: "cloudHigh", range:[[9,6], [7,6]], comp: "lower"},
  {noun: "rectangle", adjective: "dark", fileinit: "rectangleDark", range:[[1,4], [3,4]], comp: "darker"},
  {noun: "rectangle", adjective: "light", fileinit: "rectangleDark", range:[[9,6], [7,6]], comp: "lighter"},
  {noun: "banana", adjective: "ripe", fileinit: "bananaRipe", range:[[1,4], [3,4]], comp: "riper/more ripe"},
  {noun: "banana", adjective: "unripe", fileinit: "bananaRipe", range:[[9,6], [7,6]], comp: "more unripe"},
  {noun: "glass", adjective: "full", fileinit: "glassFull", range:[[2,5], [4,5]], comp: "fuller"},
  {noun: "glass", adjective: "empty", fileinit: "glassFull", range:[[9,6], [7,6]], comp: "emptier/more empty"},
  {noun: "gate", adjective: "open", fileinit: "gateOpen", range:[[2,5], [4,5]], comp: "more open"},
  {noun: "gate", adjective: "closed", fileinit: "gateOpen", range:[[6,3], [4,3]], comp: "more closed"},
  {noun: "glass", adjective: "transparent", fileinit: "glassTransparent", range:[[2,5], [4,5]], comp: "more transparent"},
  {noun: "glass", adjective: "opaque", fileinit: "glassTransparent", range:[[6,3], [4,3]], comp: "more opaque"},
  {noun: "straw", adjective: "straight", fileinit: "strawStraight", range:[[5,8], [7,8]], comp: "straighter"},
  {noun: "straw", adjective: "bent", fileinit: "strawStraight", range:[[8,5], [8,7]], comp: "more bent"},
  {noun: "cookie", adjective: "round", fileinit: "cookieRound", range:[[6,7], [4,7]], comp: "rounder"},
  {noun: "plate", adjective: "clean", fileinit: "plateClean", range:[[5,8], [7,8]], comp: "cleaner"},
  {noun: "plate", adjective: "dirty", fileinit: "plateClean", range:[[8,5], [6,5]], comp: "dirtier"},
  {noun: "toast", adjective: "burnt", fileinit: "toastBurnt", range:[[5,6], [3,6]], comp: "more burnt"},
  {noun: "paper", adjective: "torn", fileinit: "paperTorn", range:[[2,3], [2,4]], comp: "more torn"},
  {noun: "sky", adjective: "cloudy", fileinit: "skyCloudy", range:[[3,4], [2,4]], comp: "cloudier/more cloudy"},
];

allStims = _.shuffle(allStims);
