exStims = _.shuffle([
  {noun: "strawberry", adjective: "big", 
   comparative: "bigger", fileinit: "strawberryBig",
   range:[[3, 4]]},
  {noun: "plate", adjective: "clean", 
   comparative: "cleaner", 
   fileinit: "plateClean",
   range:[[7, 8]]}
]);

allStims = [{noun: "pencil", adjective: "long", 
   comparative: "longer", fileinit: "pencilLong",
   range:[[350, 360]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[310, 320]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[350, 360]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[320, 340]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[300, 320]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[280, 300]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[240, 260]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[200, 220]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[55, 60]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[50, 55]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[45, 50]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[40, 45]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[35, 40]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[30, 35]]},
  {noun: "straw", adjective: "straight", 
   comparative: "straighter", fileinit: "strawStraight",
   range:[[171, 172]]},
  {noun: "straw", adjective: "straight", 
   comparative: "straighter", fileinit: "strawStraight",
   range:[[175, 176]]},
  {noun: "straw", adjective: "straight", 
   comparative: "straighter", fileinit: "strawStraight",
   range:[[177, 178]]},
  {noun: "straw", adjective: "straight", 
   comparative: "straighter", fileinit: "strawStraight",
   range:[[173, 174]]},
  {noun: "straw", adjective: "straight", 
   comparative: "straighter", fileinit: "strawStraight",
   range:[[179, 180]]}
];

allStims = _.shuffle(allStims);
