exStims = _.shuffle([
  {noun: "strawberry", adjective: "big", 
   comparative: "bigger", fileinit: "strawberryBig",
   range:[[3, 4]]},
  {noun: "plate", adjective: "clean", 
   comparative: "cleaner", 
   fileinit: "plateClean",
   range:[[7, 8]]}
]);

allStims = [{noun: "pencil", adjective: "long", 
   comparative: "longer", fileinit: "pencilLong",
   range:[[340, 360]]},
  {noun: "pencil", adjective: "long", 
   comparative: "longer", fileinit: "pencilLong",
   range:[[140, 160]]},
  {noun: "pencil", adjective: "long", 
   comparative: "longer", fileinit: "pencilLong",
   range:[[180, 200]]},
  {noun: "pencil", adjective: "long", 
   comparative: "longer", fileinit: "pencilLong",
   range:[[220, 240]]},
  {noun: "pencil", adjective: "long", 
   comparative: "longer", fileinit: "pencilLong",
   range:[[260, 280]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[360, 380]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[320, 340]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[300, 320]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[280, 300]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[240, 260]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[200, 220]]},
  {noun: "book", adjective: "thick", 
   comparative: "thicker", fileinit: "bookThick",
   range:[[55, 60]]},
  {noun: "book", adjective: "thick", 
   comparative: "thicker", fileinit: "bookThick",
   range:[[45, 50]]},
  {noun: "book", adjective: "thick", 
   comparative: "thicker", fileinit: "bookThick",
   range:[[35, 40]]},
  {noun: "book", adjective: "thick", 
   comparative: "thicker", fileinit: "bookThick",
   range:[[25, 30]]},
  {noun: "book", adjective: "thick", 
   comparative: "thicker", fileinit: "bookThick",
   range:[[15, 20]]},
  {noun: "paintbrush", adjective: "wide", 
   comparative: "wider", fileinit: "brushWide",
   range:[[150, 160]]},
  {noun: "paintbrush", adjective: "wide", 
   comparative: "wider", fileinit: "brushWide",
   range:[[140, 150]]},
  {noun: "paintbrush", adjective: "wide", 
   comparative: "wider", fileinit: "brushWide",
   range:[[110, 120]]},
  {noun: "paintbrush", adjective: "wide", 
   comparative: "wider", fileinit: "brushWide",
   range:[[80, 90]]},
  {noun: "paintbrush", adjective: "wide", 
   comparative: "wider", fileinit: "brushWide",
   range:[[60, 70]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[50, 55]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[46, 50]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[41, 46]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[37, 41]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[33, 37]]},
  {noun: "bottle", adjective: "full", 
   comparative: "fuller", fileinit: "bottleFull",
   range:[[280, 290]]},
  {noun: "bottle", adjective: "full", 
   comparative: "fuller", fileinit: "bottleFull",
   range:[[330, 340]]},
  {noun: "bottle", adjective: "full", 
   comparative: "fuller", fileinit: "bottleFull",
   range:[[350, 360]]},
  {noun: "bottle", adjective: "full", 
   comparative: "fuller", fileinit: "bottleFull",
   range:[[380, 390]]},
  {noun: "bottle", adjective: "full", 
   comparative: "fuller", fileinit: "bottleFull",
   range:[[390, 400]]},
  {noun: "bottle", adjective: "empty", 
   comparative: "emptier", fileinit: "bottleFull",
   range:[[20, 15]]},
  {noun: "bottle", adjective: "empty", 
   comparative: "emptier", fileinit: "bottleFull",
   range:[[30, 20]]},
  {noun: "bottle", adjective: "empty", 
   comparative: "emptier", fileinit: "bottleFull",
   range:[[110, 100]]},
  {noun: "bottle", adjective: "empty", 
   comparative: "emptier", fileinit: "bottleFull",
   range:[[70, 60]]},
  {noun: "bottle", adjective: "empty", 
   comparative: "emptier", fileinit: "bottleFull",
   range:[[90, 80]]},
  {noun: "straw", adjective: "straight", 
   comparative: "straighter", fileinit: "strawStraight",
   range:[[178, 180]]},
  {noun: "straw", adjective: "straight", 
   comparative: "straighter", fileinit: "strawStraight",
   range:[[177, 180]]},
  {noun: "straw", adjective: "straight", 
   comparative: "straighter", fileinit: "strawStraight",
   range:[[175, 180]]},
  {noun: "straw", adjective: "straight", 
   comparative: "straighter", fileinit: "strawStraight",
   range:[[174, 177]]}
];

allStims = _.shuffle(allStims);
