exStims = _.shuffle([
  {noun: "strawberry", adjective: "big", 
   comparative: "bigger", fileinit: "strawberryBig",
   range:[[3, 4]]},
  {noun: "plate", adjective: "clean", 
   comparative: "cleaner", 
   fileinit: "plateClean",
   range:[[7, 8]]}
]);

allStims = [{noun: "pencil", adjective: "long", 
   comparative: "longer", fileinit: "pencilLong",
   range:[[20, 40]]},
  {noun: "pencil", adjective: "long", 
   comparative: "longer", fileinit: "pencilLong",
   range:[[240, 260]]},
  {noun: "pencil", adjective: "long", 
   comparative: "longer", fileinit: "pencilLong",
   range:[[280, 300]]},
  {noun: "pencil", adjective: "long", 
   comparative: "longer", fileinit: "pencilLong",
   range:[[400, 420]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[120, 130]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[320, 330]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[290, 300]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[260, 270]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[230, 240]]},
  {noun: "glass", adjective: "tall", 
   comparative: "taller", fileinit: "glassTall",
   range:[[450, 460]]},
  {noun: "book", adjective: "thick", 
   comparative: "thicker", fileinit: "bookThick",
   range:[[75, 80]]},
  {noun: "book", adjective: "thick", 
   comparative: "thicker", fileinit: "bookThick",
   range:[[70, 80]]},
  {noun: "book", adjective: "thick", 
   comparative: "thicker", fileinit: "bookThick",
   range:[[60, 80]]},
  {noun: "paintbrush", adjective: "wide", 
   comparative: "wider", fileinit: "brushWide",
   range:[[20, 30]]},
  {noun: "paintbrush", adjective: "wide", 
   comparative: "wider", fileinit: "brushWide",
   range:[[30, 40]]},
  {noun: "paintbrush", adjective: "wide", 
   comparative: "wider", fileinit: "brushWide",
   range:[[50, 60]]},
  {noun: "paintbrush", adjective: "wide", 
   comparative: "wider", fileinit: "brushWide",
   range:[[130, 140]]},
  {noun: "paintbrush", adjective: "wide", 
   comparative: "wider", fileinit: "brushWide",
   range:[[180, 200]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[60, 65]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[25, 30]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[65, 75]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[75, 85]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[75, 100]]},
  {noun: "feather", adjective: "dark", 
   comparative: "darker", fileinit: "featherDark",
   range:[[85, 100]]},
  {noun: "bottle", adjective: "full", 
   comparative: "fuller", fileinit: "bottleFull",
   range:[[270, 280]]},
  {noun: "bottle", adjective: "full", 
   comparative: "fuller", fileinit: "bottleFull",
   range:[[310, 320]]},
  {noun: "bottle", adjective: "full", 
   comparative: "fuller", fileinit: "bottleFull",
   range:[[400, 414]]},
  {noun: "bottle", adjective: "empty", 
   comparative: "emptier", fileinit: "bottleFull",
   range:[[15,0]]},
  {noun: "bottle", adjective: "empty", 
   comparative: "emptier", fileinit: "bottleFull",
   range:[[40,30]]},
  {noun: "bottle", adjective: "empty", 
   comparative: "emptier", fileinit: "bottleFull",
   range:[[60,50]]},
  {noun: "bottle", adjective: "empty", 
   comparative: "emptier", fileinit: "bottleFull",
   range:[[100, 90]]},
  {noun: "straw", adjective: "straight", 
   comparative: "straighter", fileinit: "strawStraight",
   range:[[170, 172]]},
  {noun: "straw", adjective: "straight", 
   comparative: "straighter", fileinit: "strawStraight",
   range:[[174, 176]]},
  {noun: "straw", adjective: "straight", 
   comparative: "straighter", fileinit: "strawStraight",
   range:[[176, 178]]},
  {noun: "straw", adjective: "straight", 
   comparative: "straighter", fileinit: "strawStraight",
   range:[[172, 174]]},
];

allStims = _.shuffle(allStims);
